
# ui portion of R shiny app -----------------------------------------------


body <- navbarPage(tags$head(includeCSS(here(data_dir, "Style/navbarpage_style.css"))),
                   introjsUI(),
                   theme = shinytheme("flatly"), collapsible = TRUE,
                   title = div(img(src="https://uw-s3-cdn.s3.us-west-2.amazonaws.com/wp-content/uploads/sites/98/2014/09/07214416/W-Logo_White.png",width= "73px", height="45px"),  strong(toupper("Global Vaccine Index Dashboard"))),
                   tabPanel("Visualizations",
                            sidebarPanel(
                              h4(strong("Vaccination Improvement Potential (VIP) Index Ranking Table")),
                              sliderInput("year", "Year", value = 2019, min = 1990, max = 2019, step=1, sep = "", 
                                          animate = TRUE),
                              fluidRow(column(8,radioButtons("sdi_group_present","2019 SDI Group", choices = c("All"="all","Low" ="low","Medium" = "medium","High" = "high"),inline = TRUE)),
                                       column(4,
                                              #tags$i
                                              # class = "glyphicon glyphicon-info-sign", 
                                              # style = "color:#2c3e50;;",
                                              # title = "The Socio-demographic Index (SDI) is a summary measure that identifies where countries sit on the spectrum of development."
                                              #))),
                                              dropMenu(
                                                circleButton(label = "What is SDI?","What is SDI?", inputId='sdiinfo',icon = icon('info')),
                                                h4(strong('SDI')),
                                                h5('The Socio-demographic Index (SDI) is a summary measure that identifies where countries sit on the spectrum of development.'),
                                                placement = "bottom",
                                                arrow = TRUE),style='text-align:center')),
                              selectInput("region_table", "Regions", selected = NULL, choices = c("All",unique(index_results$region))),
                              tags$style(HTML('table.dataTable tr.selected td, table.dataTable td.selected {background-color: #92c9e8 !important;}')),
                              DT::dataTableOutput("table")),
                            mainPanel(
                              div(class="outer",absolutePanel(fixed=FALSE, width = "100%", 
                                                              draggable = FALSE, height = "100%",
                                                              tags$style(type="text/css",
                                                                         ".shiny-output-error { visibility: hidden; }",
                                                                         ".shiny-output-error:before { visibility: hidden; }"
                                                              ),
                                                              tabsetPanel(id = "t1",
                                                                          tabPanel("Vaccination Improvement",value="t_sdi",
                                                                                   fluidRow(column(6, " ", style='padding:10px;')),
                                                                                   fluidRow(column(width = 9,h4(strong(textOutput("yeartitle")),style='text-align:left')),
                                                                                            column(width = 3,div(switchInput(
                                                                                              inputId = "view",
                                                                                              # label = "Display",
                                                                                              onLabel = "Table",
                                                                                              offLabel = "Map",
                                                                                              value = FALSE,
                                                                                              labelWidth = "50px")))),
                                                                                   conditionalPanel("!input.view",
                                                                                                    fluidRow(column(12, " ", style='padding:3px;')),
                                                                                                    fluidRow(column(10, radioButtons(inputId = "show",label = NULL,
                                                                                                                                     choices = c("Vaccination Improvement Potential (VIP) Index","VIP Index Component"),
                                                                                                                                     selected = "Vaccination Improvement Potential (VIP) Index",
                                                                                                                                     inline = TRUE)), 
                                                                                                             column(2,
                                                                                                                    dropMenu(
                                                                                                                      circleButton(label = "", inputId='info',icon = icon('info')),
                                                                                                                      h4(strong('Index Mapper')),
                                                                                                                      h5('The Vaccine Improvement Index assesses a country’s potential to improve its immunization rates.'),
                                                                                                                      h5("A higher number (or darker shading on the map) indicates a better score."),
                                                                                                                      placement = "bottom",
                                                                                                                      arrow = TRUE))),
                                                                                                    conditionalPanel("input.show == 'Vaccination Improvement Potential (VIP) Index'",
                                                                                                                     fluidRow(column(12, " ", style='padding:3px;')),
                                                                                                                     fluidRow(column(12,plotlyOutput("index_map",height = "40vh")),column(1,"")),
                                                                                                                     fluidRow(column(width = 12, "Select locations in left VIP Index Ranking Table for comparison",
                                                                                                                                     style='font-family:Avenir, Helvetica;font-size:30;text-align:center')),
                                                                                                                     fluidRow(column(10,''),column(2,
                                                                                                                                                   dropMenu(
                                                                                                                                                     circleButton(label = "", inputId='info2',icon = icon('info')),
                                                                                                                                                     h4(strong('Time Series of Vaccination Improvement Potential (VIP) Index')),
                                                                                                                                                     h5('The index value is estimated yearly between 1990 and 2019, in order to track improvement or change over time. '),
                                                                                                                                                     placement = "bottom",
                                                                                                                                                     arrow = TRUE))),
                                                                                                                     fluidRow(column(12, plotlyOutput("index_trend_plot_multi",height = "30vh"))),column(1,"")),
                                                                                                    fluidRow(column(12, " ", style='padding:2px;')),
                                                                                                    conditionalPanel("input.show == 'VIP Index Component'",
                                                                                                                     #fluidRow(column(4,selectInput("indicators", "Indicator:",choices=c("SDI","Development Assistance Per Total Health Spending Categorical","Total Health Spending per Person","Government Health Spending per Total Health Spending",
                                                                                                                     #                                                                  "HAQI","Corruption Perception Index","Skilled Attendants at Birth","Immigrant Population (%)","Urbanicity (%)","Agreement Vaccines are Safe",
                                                                                                                     #                                                                 "Agreement Vaccines are Important","Agreement Vaccines are Effective"),width = "500px")),
                                                                                                                     fluidRow(column(5,selectInput("indicators", "Indicator:",choices=c("Socio-demographic Index","Eligibility to Receive DAH","Total Health Spending per Person","Government Health Spending per Total Health Spending",
                                                                                                                                                                                        "Development Assistance per Person","HAQI","Corruption Perception Index","Skilled Attendants at Birth","Immigrant Population (%)","Urbanicity (%)"),width = "500px"))),
                                                                                                                     fluidRow(column(11,plotlyOutput("indicator_map",height = "43vh")),column(1,"")),
                                                                                                                     column(width = 12, "Select location in left VIP Index Ranking Table for comparison",
                                                                                                                            style='font-family:Avenir, Helvetica;font-size:30;text-align:center;padding:2px'),
                                                                                                                     fluidRow(column(11, plotlyOutput("indicator_trend_plot_multi",height = "27vh")),column(1,""))
                                                                                                    )),
                                                                                   conditionalPanel("input.view",
                                                                                                    fluidRow(column(11, DT::dataTableOutput("indextable")),column(1,"")))),
                                                                          tabPanel("Vaccination Trends", value = "t_vac",
                                                                                   fluidRow(column(width = 11,h4(strong(htmlOutput("content_vac"))))),
                                                                                   fluidRow(column(width = 10, "Select location in left VIP Ranking table",
                                                                                                   style='font-family:Avenir, Helvetica;font-size:30;text-align:left'),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info3',icon = icon('info')),
                                                                                                     h4(strong('Vaccination Trends')),
                                                                                                     h5('Recommended vaccinations and the date they began to be used can differ between countries. This visual shows how vaccination coverage has changed over time in a particular location.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                                                   radioButtons("vaccine_plot","Plot type:", choices = c("Time Series of Vaccine Coverage" ="line_trend","Single Year Vaccine Coverage"="bar_plot"),inline = TRUE),
                                                                                   fluidRow(column(11,plotlyOutput("all_vaccine_plot",height = "50vh")),column(1,""))),
                                                                          tabPanel("Mortality & Disability Trends",value = "d_vac",
                                                                                   fluidRow(column(width = 11,h4(strong(htmlOutput("content_dis"))))),
                                                                                   fluidRow(column(width = 10, "Select location in left VIP Index Ranking Table",
                                                                                                   style='font-family:Avenir, Helvetica;font-size:30;text-align:left'),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info4',icon = icon('info')),
                                                                                                     h4(strong('Mortality and Disability Trends')),
                                                                                                     h5('This graphic shows how the number of deaths or number of people infected have changed between the years 1990 to 2019. The diseases or disabilities presented on this graph can all be prevented with a vaccine administered at the appropriate time.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   radioButtons("disease_estimate","Choose y-axis:", choices = c("Number Value"="number_val","Percent Value" ="percent_val","Rate Value" = "rate_val"),inline = TRUE),
                                                                                   plotlyOutput("all_disease_plot", height = "35vh"),
                                                                                   fluidRow(column(10, " ", style='padding:30px;'),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info5',icon = icon('info')),
                                                                                                     h4(strong('Time series of years lived in less than ideal health')),
                                                                                                     h5('This graphic shows the combined impact of a disease in a country and how it changes from year to year.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   plotlyOutput("all_disability_plot", height = "35vh")),
                                                                          tabPanel(paste0("Vaccination & Corresponding Disease Trends"),value="vac_dis_tab",
                                                                                   fluidRow(column(12,h4(strong(htmlOutput("content_vac_dis"))))),
                                                                                   fluidRow(column(10,selectInput("vaccinations", "Vaccination:",choices=NULL)),
                                                                                            column(2,
                                                                                                   dropMenu(
                                                                                                     circleButton(label = "", inputId='info6',icon = icon('info')),
                                                                                                     h4(strong('Vaccination and Disease Trends')),
                                                                                                     h5('This graphic compares vaccination rates and the death rate from the diseases that vaccines help prevent.'),
                                                                                                     placement = "bottom",
                                                                                                     arrow = TRUE))),
                                                                                   fluidRow(column(12,plotlyOutput("selected_vac_dis_plot",height = "40vh"))),
                                                                                   fluidRow(
                                                                                     column(3,
                                                                                            h4("BCG"),
                                                                                            helpText("Bacillus Calmette–Guérin"),
                                                                                            DT::dataTableOutput("BCGtable")),
                                                                                     column(3,
                                                                                            h4("DTP1 & DTP3"),
                                                                                            helpText("Diphtheria, tetanus, pertussis"),
                                                                                            DT::dataTableOutput("DTPtable")),
                                                                                     column(2,
                                                                                            h4("HepB3"),
                                                                                            helpText("Hepatitis B"),
                                                                                            DT::dataTableOutput("HepB3table")), 
                                                                                     column(2,
                                                                                            h4("MCV1 & MCV2"),
                                                                                            helpText("Measles"),
                                                                                            DT::dataTableOutput("MCVtable")), 
                                                                                     column(1,
                                                                                            h4("RotaC"),
                                                                                            helpText("Rotavirus"),
                                                                                            DT::dataTableOutput("RotaCtable"))
                                                                                   )),
                                                                          tabPanel("Data Explorer",
                                                                                   fluidRow(column(5, " ", style='padding:5px;')),
                                                                                   fluidRow(column(9, radioButtons("dataset","Choose Dataset", choices = c("Improvement Index"= "improvement index","Vaccine Trends" = "vaccine trends","Disease Trends" = "disease trends","Data Dictionary" = "data dictionary"),inline = TRUE)),
                                                                                            column(3, style = "margin-top: 10px;",div(downloadButton("download","Download Raw Data"),style='float:right'))),
                                                                                   fluidRow(column(width = 9, "Download custom datasets from the variables that were used to create visuals on the previous tabs. ",
                                                                                                   style='font-family:Avenir, Helvetica;font-size:30;text-align:left')),
                                                                                   fluidRow(column(12,DT::dataTableOutput("alldatatable") %>% withSpinner(color="#4b2e83")))
                                                                          )
                                                              ),
                                                              tags$head(tags$style('ul.nav.nav-tabs { overflow-y: hidden; display: flex;}')
                                                              ), 
                              ))))
                   ,
                   tabPanel("Sample Report",
                            sidebarPanel(
                              h4(strong("Sample Report: for Nigeria")),
                              fluidRow(column(6, " ", style='padding:70px;')),
                              fluidRow(column(12,h5(strong(textOutput("report_nig_title"))))),
                              fluidRow(column(6, " ", style='padding:10px;')),
                              fluidRow(column(12,textOutput("report_nig_body"))),
                              fluidRow(column(6, " ", style='padding:90px;')),
                              tags$head(tags$style("{color: #0060bf; font-size: 20px;}")),
                              downloadButton(
                                outputId = "report",
                                label = "Download Report"
                              ),
                              width = 4),
                            mainPanel(
                              tabsetPanel(id="t2",
                                          tabPanel("Comparison",value = "comp_index",
                                                   fluidRow(column(8, " ", style='padding:20px;')),
                                                   fluidRow(column(4,radioButtons("sdi_group_present_comp","2019 SDI Group", choices = c("All"="all","Low" ="low","Medium" = "medium","High" = "high"),selected="low",inline = TRUE)),
                                                            column(4,selectInput("region", "Regions", choices = unique(index_results$region))),
                                                            column(4,selectInput(
                                                              inputId = "my_multi",
                                                              label = "Search Country :",
                                                              choices = unique(merged_data_for_vacii_sdi$location),
                                                              selected = "Nigeria",
                                                              selectize = TRUE,
                                                              multiple=TRUE))),
                                                   fluidRow(column(8, " ", style='padding:20px;')),
                                                   fluidRow(column(12, plotlyOutput("index_trend_plot_com",height = "40vh"))),column(1,"")),
                                          tabPanel("Vaccination Trends",value = "report_vt",
                                                   fluidRow(column(width = 11,h4(strong("Nigeria")))),
                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                   fluidRow(column(11,plotlyOutput("nigeria_vaccine_plot",height = "55vh")),column(1,""))),
                                          tabPanel("Mortality and Disability Trends",value = "report_md",
                                                   fluidRow(column(width = 11,h4(strong("Nigeria")))),
                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                   fluidRow(column(12,plotlyOutput("nigeria_disability_plot", height = "45vh")))),
                                          tabPanel("Vaccination and Corresponding Diseases Trends",value = "report_vcdt",
                                                   fluidRow(column(width = 11,h4(strong("Nigeria")))),
                                                   fluidRow(column(width = 11,h5(strong("Selected Vaccination: MCV1")))),
                                                   fluidRow(column(8, " ", style='padding:10px;')),
                                                   fluidRow(column(12,plotlyOutput("selected_nigeria_vac_dis_plot", height = "50vh")))
                                          )))),
                   tabPanel("About This Site",
                            tags$div(
                              tags$h4(strong("Website Last Updated")),
                              h6(paste0(Sys.Date())),
                              tags$h4(strong("Data Last Updated")),
                              h6(paste0("2022-11-03")),
                              tags$br(),
                              tags$h4(strong("Background")),
                              "Improving routine vaccination coverage is an important global health goal. Reaching and maintaining high vaccination coverage helps avoid death and illness from many preventable diseases, especially in children.",
                              tags$br(),tags$br(),"The factors that drive vaccination coverage are many and can differ between countries. The Global Vaccine Index Project is an attempt to organize data on several of these factors into a single index that allows a quick comparison between locations and across time. This project builds on prior research that identified factors that contribute to higher vaccination rates in multiple low and middle income countries.",
                              tags$br(),tags$br(),"As part of the Global Vaccine Index Project, this website offers data and resources to people interested in learning more about vaccination trends, vaccine-preventable diseases, and information on the importance of vaccines to promote health and well-being in communities around the world. ",
                              tags$br(),tags$br(),tags$h4(strong("Sources")),
                              "1. Global Burden of Disease Collaborative Network.",
                              tags$a("Global Burden of Disease Study 2020, Release 1 (GBD 2020 R1) Routine Childhood Vaccination Coverage 1980-2019 [Internet]",target="_blank", href="https://ghdx.healthdata.org/record/ihme-data/gbd-2020-routine-childhood-vaccination-coverage-1980-2019"),
                              "Institute for Health Metrics and Evaluation (IHME); 2021 [cited 2021 Jul 21].",
                              tags$br(),
                              "2. Barau I, Zubairu M, Mwanza MN, Seaman VY. Improving polio vaccination coverage in Nigeria through the use of geographic information system technology. J Infect Dis. 2014 Nov 1;210 Suppl 1:S102-110.",
                              tags$br(),
                              "3. National Primary Health Care Development Agency.",
                              tags$a("Nigeria: National Routine Immunization Strategic Plan 2013-2015 | NITAG RESOURCE CENTER [Internet].",target="_blank",href="https://www.jhsph.edu/research/centers-and-institutes/ivac/resources/Nigeria-NRISP-Technical-Policy.pdf"),
                              "2013 [cited 2021 Sep 22]",
                              tags$br(),
                              "4. Oku A, Oyo-Ita A, Glenton C, Fretheim A, Ames H, Muloliwa A, et al. Communication strategies to promote the uptake of childhood vaccination in Nigeria: a systematic map. Glob Health Action. 2016 Feb 12;9(1).",
                              tags$br(),
                              "5. Ado JM, Etsano A, Shuaib F, Damisa E, Mkanda P, Gasasira A, et al. Progress toward poliomyelitis eradication in Nigeria. J Infect Dis. 2014 Nov 1;210 Suppl 1:S40-49.",
                              tags$br(),
                              "6. Gunnala R, Ogbuanu IU, Adegoke OJ, Scobie HM, Uba BV, Wannemuehler KA, et al. Routine Vaccination Coverage in Northern Nigeria: Results from 40 District-Level Cluster Surveys, 2014-2015. Borrow R, editor. PLOS ONE. 2016 Dec 9;11(12):e0167835.",
                              tags$br(),
                              "7. Oleribe O, Kumar V, Awosika-Olumo A, Taylor SD."
                              ,
                              tags$a("Individual and socioeconomic factors associated with childhood immunization coverage in Nigeria. Pan Afr Med J [Internet].",target="_blank",href="https://panafrican-med-journal.com/content/article/26/220/full/"),
                              "2017 [cited 2021 Sep 27];26."
                            )
                   )
)
